// Generated by the protocol buffer compiler.  DO NOT EDIT!

package org.devtcg.five.meta.data;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Artist extends
      com.google.protobuf.GeneratedMessage {
    // Use Artist.newBuilder() to construct.
    private Artist() {}
    
    private static final Artist defaultInstance = new Artist();
    public static Artist getDefaultInstance() {
      return defaultInstance;
    }
    
    public Artist getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.devtcg.five.meta.data.Protos.internal_static_Artist_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.devtcg.five.meta.data.Protos.internal_static_Artist_fieldAccessorTable;
    }
    
    // required int64 id = 1;
    private boolean hasId;
    private long id_ = 0L;
    public boolean hasId() { return hasId; }
    public long getId() { return id_; }
    
    // required int64 syncTime = 2;
    private boolean hasSyncTime;
    private long syncTime_ = 0L;
    public boolean hasSyncTime() { return hasSyncTime; }
    public long getSyncTime() { return syncTime_; }
    
    // optional string mbid = 3;
    private boolean hasMbid;
    private java.lang.String mbid_ = "";
    public boolean hasMbid() { return hasMbid; }
    public java.lang.String getMbid() { return mbid_; }
    
    // required string name = 4;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional int64 discoveryDate = 5;
    private boolean hasDiscoveryDate;
    private long discoveryDate_ = 0L;
    public boolean hasDiscoveryDate() { return hasDiscoveryDate; }
    public long getDiscoveryDate() { return discoveryDate_; }
    
    public static org.devtcg.five.meta.data.Protos.Artist parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Artist parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Artist parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Artist parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Artist parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Artist parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Artist parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Artist parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(org.devtcg.five.meta.data.Protos.Artist prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using org.devtcg.five.meta.data.Protos.Artist.newBuilder()
      private Builder() {}
      
      org.devtcg.five.meta.data.Protos.Artist result = new org.devtcg.five.meta.data.Protos.Artist();
      
      @Override
      protected org.devtcg.five.meta.data.Protos.Artist internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new org.devtcg.five.meta.data.Protos.Artist();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.devtcg.five.meta.data.Protos.Artist.getDescriptor();
      }
      
      public org.devtcg.five.meta.data.Protos.Artist getDefaultInstanceForType() {
        return org.devtcg.five.meta.data.Protos.Artist.getDefaultInstance();
      }
      
      public org.devtcg.five.meta.data.Protos.Artist build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private org.devtcg.five.meta.data.Protos.Artist buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.devtcg.five.meta.data.Protos.Artist buildPartial() {
        org.devtcg.five.meta.data.Protos.Artist returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required int64 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public long getId() {
        return result.getId();
      }
      public Builder setId(long value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0L;
        return this;
      }
      
      // required int64 syncTime = 2;
      public boolean hasSyncTime() {
        return result.hasSyncTime();
      }
      public long getSyncTime() {
        return result.getSyncTime();
      }
      public Builder setSyncTime(long value) {
        result.hasSyncTime = true;
        result.syncTime_ = value;
        return this;
      }
      public Builder clearSyncTime() {
        result.hasSyncTime = false;
        result.syncTime_ = 0L;
        return this;
      }
      
      // optional string mbid = 3;
      public boolean hasMbid() {
        return result.hasMbid();
      }
      public java.lang.String getMbid() {
        return result.getMbid();
      }
      public Builder setMbid(java.lang.String value) {
        result.hasMbid = true;
        result.mbid_ = value;
        return this;
      }
      public Builder clearMbid() {
        result.hasMbid = false;
        result.mbid_ = "";
        return this;
      }
      
      // required string name = 4;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = "";
        return this;
      }
      
      // optional int64 discoveryDate = 5;
      public boolean hasDiscoveryDate() {
        return result.hasDiscoveryDate();
      }
      public long getDiscoveryDate() {
        return result.getDiscoveryDate();
      }
      public Builder setDiscoveryDate(long value) {
        result.hasDiscoveryDate = true;
        result.discoveryDate_ = value;
        return this;
      }
      public Builder clearDiscoveryDate() {
        result.hasDiscoveryDate = false;
        result.discoveryDate_ = 0L;
        return this;
      }
    }
    
    static {
      org.devtcg.five.meta.data.Protos.getDescriptor();
    }
  }
  
  public static final class Album extends
      com.google.protobuf.GeneratedMessage {
    // Use Album.newBuilder() to construct.
    private Album() {}
    
    private static final Album defaultInstance = new Album();
    public static Album getDefaultInstance() {
      return defaultInstance;
    }
    
    public Album getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.devtcg.five.meta.data.Protos.internal_static_Album_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.devtcg.five.meta.data.Protos.internal_static_Album_fieldAccessorTable;
    }
    
    // required int64 id = 1;
    private boolean hasId;
    private long id_ = 0L;
    public boolean hasId() { return hasId; }
    public long getId() { return id_; }
    
    // required int64 syncTime = 2;
    private boolean hasSyncTime;
    private long syncTime_ = 0L;
    public boolean hasSyncTime() { return hasSyncTime; }
    public long getSyncTime() { return syncTime_; }
    
    // required int64 artistId = 3;
    private boolean hasArtistId;
    private long artistId_ = 0L;
    public boolean hasArtistId() { return hasArtistId; }
    public long getArtistId() { return artistId_; }
    
    // optional string mbid = 4;
    private boolean hasMbid;
    private java.lang.String mbid_ = "";
    public boolean hasMbid() { return hasMbid; }
    public java.lang.String getMbid() { return mbid_; }
    
    // required string name = 5;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional int64 discoveryDate = 6;
    private boolean hasDiscoveryDate;
    private long discoveryDate_ = 0L;
    public boolean hasDiscoveryDate() { return hasDiscoveryDate; }
    public long getDiscoveryDate() { return discoveryDate_; }
    
    // optional int64 releaseDate = 7;
    private boolean hasReleaseDate;
    private long releaseDate_ = 0L;
    public boolean hasReleaseDate() { return hasReleaseDate; }
    public long getReleaseDate() { return releaseDate_; }
    
    public static org.devtcg.five.meta.data.Protos.Album parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Album parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Album parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Album parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Album parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Album parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Album parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Album parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(org.devtcg.five.meta.data.Protos.Album prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using org.devtcg.five.meta.data.Protos.Album.newBuilder()
      private Builder() {}
      
      org.devtcg.five.meta.data.Protos.Album result = new org.devtcg.five.meta.data.Protos.Album();
      
      @Override
      protected org.devtcg.five.meta.data.Protos.Album internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new org.devtcg.five.meta.data.Protos.Album();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.devtcg.five.meta.data.Protos.Album.getDescriptor();
      }
      
      public org.devtcg.five.meta.data.Protos.Album getDefaultInstanceForType() {
        return org.devtcg.five.meta.data.Protos.Album.getDefaultInstance();
      }
      
      public org.devtcg.five.meta.data.Protos.Album build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private org.devtcg.five.meta.data.Protos.Album buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.devtcg.five.meta.data.Protos.Album buildPartial() {
        org.devtcg.five.meta.data.Protos.Album returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required int64 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public long getId() {
        return result.getId();
      }
      public Builder setId(long value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0L;
        return this;
      }
      
      // required int64 syncTime = 2;
      public boolean hasSyncTime() {
        return result.hasSyncTime();
      }
      public long getSyncTime() {
        return result.getSyncTime();
      }
      public Builder setSyncTime(long value) {
        result.hasSyncTime = true;
        result.syncTime_ = value;
        return this;
      }
      public Builder clearSyncTime() {
        result.hasSyncTime = false;
        result.syncTime_ = 0L;
        return this;
      }
      
      // required int64 artistId = 3;
      public boolean hasArtistId() {
        return result.hasArtistId();
      }
      public long getArtistId() {
        return result.getArtistId();
      }
      public Builder setArtistId(long value) {
        result.hasArtistId = true;
        result.artistId_ = value;
        return this;
      }
      public Builder clearArtistId() {
        result.hasArtistId = false;
        result.artistId_ = 0L;
        return this;
      }
      
      // optional string mbid = 4;
      public boolean hasMbid() {
        return result.hasMbid();
      }
      public java.lang.String getMbid() {
        return result.getMbid();
      }
      public Builder setMbid(java.lang.String value) {
        result.hasMbid = true;
        result.mbid_ = value;
        return this;
      }
      public Builder clearMbid() {
        result.hasMbid = false;
        result.mbid_ = "";
        return this;
      }
      
      // required string name = 5;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = "";
        return this;
      }
      
      // optional int64 discoveryDate = 6;
      public boolean hasDiscoveryDate() {
        return result.hasDiscoveryDate();
      }
      public long getDiscoveryDate() {
        return result.getDiscoveryDate();
      }
      public Builder setDiscoveryDate(long value) {
        result.hasDiscoveryDate = true;
        result.discoveryDate_ = value;
        return this;
      }
      public Builder clearDiscoveryDate() {
        result.hasDiscoveryDate = false;
        result.discoveryDate_ = 0L;
        return this;
      }
      
      // optional int64 releaseDate = 7;
      public boolean hasReleaseDate() {
        return result.hasReleaseDate();
      }
      public long getReleaseDate() {
        return result.getReleaseDate();
      }
      public Builder setReleaseDate(long value) {
        result.hasReleaseDate = true;
        result.releaseDate_ = value;
        return this;
      }
      public Builder clearReleaseDate() {
        result.hasReleaseDate = false;
        result.releaseDate_ = 0L;
        return this;
      }
    }
    
    static {
      org.devtcg.five.meta.data.Protos.getDescriptor();
    }
  }
  
  public static final class Song extends
      com.google.protobuf.GeneratedMessage {
    // Use Song.newBuilder() to construct.
    private Song() {}
    
    private static final Song defaultInstance = new Song();
    public static Song getDefaultInstance() {
      return defaultInstance;
    }
    
    public Song getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.devtcg.five.meta.data.Protos.internal_static_Song_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.devtcg.five.meta.data.Protos.internal_static_Song_fieldAccessorTable;
    }
    
    // required int64 id = 1;
    private boolean hasId;
    private long id_ = 0L;
    public boolean hasId() { return hasId; }
    public long getId() { return id_; }
    
    // required int64 syncTime = 2;
    private boolean hasSyncTime;
    private long syncTime_ = 0L;
    public boolean hasSyncTime() { return hasSyncTime; }
    public long getSyncTime() { return syncTime_; }
    
    // required int64 artistId = 3;
    private boolean hasArtistId;
    private long artistId_ = 0L;
    public boolean hasArtistId() { return hasArtistId; }
    public long getArtistId() { return artistId_; }
    
    // required int64 albumId = 4;
    private boolean hasAlbumId;
    private long albumId_ = 0L;
    public boolean hasAlbumId() { return hasAlbumId; }
    public long getAlbumId() { return albumId_; }
    
    // optional string mbid = 5;
    private boolean hasMbid;
    private java.lang.String mbid_ = "";
    public boolean hasMbid() { return hasMbid; }
    public java.lang.String getMbid() { return mbid_; }
    
    // optional string mimeType = 6;
    private boolean hasMimeType;
    private java.lang.String mimeType_ = "";
    public boolean hasMimeType() { return hasMimeType; }
    public java.lang.String getMimeType() { return mimeType_; }
    
    // optional int32 bitrate = 7;
    private boolean hasBitrate;
    private int bitrate_ = 0;
    public boolean hasBitrate() { return hasBitrate; }
    public int getBitrate() { return bitrate_; }
    
    // optional int64 filesize = 8;
    private boolean hasFilesize;
    private long filesize_ = 0L;
    public boolean hasFilesize() { return hasFilesize; }
    public long getFilesize() { return filesize_; }
    
    // optional int32 length = 9;
    private boolean hasLength;
    private int length_ = 0;
    public boolean hasLength() { return hasLength; }
    public int getLength() { return length_; }
    
    // required string title = 10;
    private boolean hasTitle;
    private java.lang.String title_ = "";
    public boolean hasTitle() { return hasTitle; }
    public java.lang.String getTitle() { return title_; }
    
    // optional int32 track = 11;
    private boolean hasTrack;
    private int track_ = 0;
    public boolean hasTrack() { return hasTrack; }
    public int getTrack() { return track_; }
    
    public static org.devtcg.five.meta.data.Protos.Song parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Song parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Song parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Song parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Song parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Song parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Song parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Song parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(org.devtcg.five.meta.data.Protos.Song prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using org.devtcg.five.meta.data.Protos.Song.newBuilder()
      private Builder() {}
      
      org.devtcg.five.meta.data.Protos.Song result = new org.devtcg.five.meta.data.Protos.Song();
      
      @Override
      protected org.devtcg.five.meta.data.Protos.Song internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new org.devtcg.five.meta.data.Protos.Song();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.devtcg.five.meta.data.Protos.Song.getDescriptor();
      }
      
      public org.devtcg.five.meta.data.Protos.Song getDefaultInstanceForType() {
        return org.devtcg.five.meta.data.Protos.Song.getDefaultInstance();
      }
      
      public org.devtcg.five.meta.data.Protos.Song build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private org.devtcg.five.meta.data.Protos.Song buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.devtcg.five.meta.data.Protos.Song buildPartial() {
        org.devtcg.five.meta.data.Protos.Song returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required int64 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public long getId() {
        return result.getId();
      }
      public Builder setId(long value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0L;
        return this;
      }
      
      // required int64 syncTime = 2;
      public boolean hasSyncTime() {
        return result.hasSyncTime();
      }
      public long getSyncTime() {
        return result.getSyncTime();
      }
      public Builder setSyncTime(long value) {
        result.hasSyncTime = true;
        result.syncTime_ = value;
        return this;
      }
      public Builder clearSyncTime() {
        result.hasSyncTime = false;
        result.syncTime_ = 0L;
        return this;
      }
      
      // required int64 artistId = 3;
      public boolean hasArtistId() {
        return result.hasArtistId();
      }
      public long getArtistId() {
        return result.getArtistId();
      }
      public Builder setArtistId(long value) {
        result.hasArtistId = true;
        result.artistId_ = value;
        return this;
      }
      public Builder clearArtistId() {
        result.hasArtistId = false;
        result.artistId_ = 0L;
        return this;
      }
      
      // required int64 albumId = 4;
      public boolean hasAlbumId() {
        return result.hasAlbumId();
      }
      public long getAlbumId() {
        return result.getAlbumId();
      }
      public Builder setAlbumId(long value) {
        result.hasAlbumId = true;
        result.albumId_ = value;
        return this;
      }
      public Builder clearAlbumId() {
        result.hasAlbumId = false;
        result.albumId_ = 0L;
        return this;
      }
      
      // optional string mbid = 5;
      public boolean hasMbid() {
        return result.hasMbid();
      }
      public java.lang.String getMbid() {
        return result.getMbid();
      }
      public Builder setMbid(java.lang.String value) {
        result.hasMbid = true;
        result.mbid_ = value;
        return this;
      }
      public Builder clearMbid() {
        result.hasMbid = false;
        result.mbid_ = "";
        return this;
      }
      
      // optional string mimeType = 6;
      public boolean hasMimeType() {
        return result.hasMimeType();
      }
      public java.lang.String getMimeType() {
        return result.getMimeType();
      }
      public Builder setMimeType(java.lang.String value) {
        result.hasMimeType = true;
        result.mimeType_ = value;
        return this;
      }
      public Builder clearMimeType() {
        result.hasMimeType = false;
        result.mimeType_ = "";
        return this;
      }
      
      // optional int32 bitrate = 7;
      public boolean hasBitrate() {
        return result.hasBitrate();
      }
      public int getBitrate() {
        return result.getBitrate();
      }
      public Builder setBitrate(int value) {
        result.hasBitrate = true;
        result.bitrate_ = value;
        return this;
      }
      public Builder clearBitrate() {
        result.hasBitrate = false;
        result.bitrate_ = 0;
        return this;
      }
      
      // optional int64 filesize = 8;
      public boolean hasFilesize() {
        return result.hasFilesize();
      }
      public long getFilesize() {
        return result.getFilesize();
      }
      public Builder setFilesize(long value) {
        result.hasFilesize = true;
        result.filesize_ = value;
        return this;
      }
      public Builder clearFilesize() {
        result.hasFilesize = false;
        result.filesize_ = 0L;
        return this;
      }
      
      // optional int32 length = 9;
      public boolean hasLength() {
        return result.hasLength();
      }
      public int getLength() {
        return result.getLength();
      }
      public Builder setLength(int value) {
        result.hasLength = true;
        result.length_ = value;
        return this;
      }
      public Builder clearLength() {
        result.hasLength = false;
        result.length_ = 0;
        return this;
      }
      
      // required string title = 10;
      public boolean hasTitle() {
        return result.hasTitle();
      }
      public java.lang.String getTitle() {
        return result.getTitle();
      }
      public Builder setTitle(java.lang.String value) {
        result.hasTitle = true;
        result.title_ = value;
        return this;
      }
      public Builder clearTitle() {
        result.hasTitle = false;
        result.title_ = "";
        return this;
      }
      
      // optional int32 track = 11;
      public boolean hasTrack() {
        return result.hasTrack();
      }
      public int getTrack() {
        return result.getTrack();
      }
      public Builder setTrack(int value) {
        result.hasTrack = true;
        result.track_ = value;
        return this;
      }
      public Builder clearTrack() {
        result.hasTrack = false;
        result.track_ = 0;
        return this;
      }
    }
    
    static {
      org.devtcg.five.meta.data.Protos.getDescriptor();
    }
  }
  
  public static final class Record extends
      com.google.protobuf.GeneratedMessage {
    // Use Record.newBuilder() to construct.
    private Record() {}
    
    private static final Record defaultInstance = new Record();
    public static Record getDefaultInstance() {
      return defaultInstance;
    }
    
    public Record getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.devtcg.five.meta.data.Protos.internal_static_Record_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.devtcg.five.meta.data.Protos.internal_static_Record_fieldAccessorTable;
    }
    
    public static enum Type {
      ARTIST(0, 1),
      ALBUM(1, 2),
      SONG(2, 3),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 1: return ARTIST;
          case 2: return ALBUM;
          case 3: return SONG;
          default: return null;
        }
      }
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.devtcg.five.meta.data.Protos.Record.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        ARTIST, ALBUM, SONG, 
      };
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        org.devtcg.five.meta.data.Protos.getDescriptor();
      }
    }
    
    // required .Record.Type type = 1;
    private boolean hasType;
    private org.devtcg.five.meta.data.Protos.Record.Type type_ = org.devtcg.five.meta.data.Protos.Record.Type.ARTIST;
    public boolean hasType() { return hasType; }
    public org.devtcg.five.meta.data.Protos.Record.Type getType() { return type_; }
    
    // optional .Artist artist = 2;
    private boolean hasArtist;
    private org.devtcg.five.meta.data.Protos.Artist artist_ = org.devtcg.five.meta.data.Protos.Artist.getDefaultInstance();
    public boolean hasArtist() { return hasArtist; }
    public org.devtcg.five.meta.data.Protos.Artist getArtist() { return artist_; }
    
    // optional .Album album = 3;
    private boolean hasAlbum;
    private org.devtcg.five.meta.data.Protos.Album album_ = org.devtcg.five.meta.data.Protos.Album.getDefaultInstance();
    public boolean hasAlbum() { return hasAlbum; }
    public org.devtcg.five.meta.data.Protos.Album getAlbum() { return album_; }
    
    // optional .Song song = 4;
    private boolean hasSong;
    private org.devtcg.five.meta.data.Protos.Song song_ = org.devtcg.five.meta.data.Protos.Song.getDefaultInstance();
    public boolean hasSong() { return hasSong; }
    public org.devtcg.five.meta.data.Protos.Song getSong() { return song_; }
    
    public static org.devtcg.five.meta.data.Protos.Record parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Record parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Record parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Record parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Record parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Record parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Record parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.devtcg.five.meta.data.Protos.Record parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(org.devtcg.five.meta.data.Protos.Record prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using org.devtcg.five.meta.data.Protos.Record.newBuilder()
      private Builder() {}
      
      org.devtcg.five.meta.data.Protos.Record result = new org.devtcg.five.meta.data.Protos.Record();
      
      @Override
      protected org.devtcg.five.meta.data.Protos.Record internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new org.devtcg.five.meta.data.Protos.Record();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.devtcg.five.meta.data.Protos.Record.getDescriptor();
      }
      
      public org.devtcg.five.meta.data.Protos.Record getDefaultInstanceForType() {
        return org.devtcg.five.meta.data.Protos.Record.getDefaultInstance();
      }
      
      public org.devtcg.five.meta.data.Protos.Record build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private org.devtcg.five.meta.data.Protos.Record buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.devtcg.five.meta.data.Protos.Record buildPartial() {
        org.devtcg.five.meta.data.Protos.Record returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required .Record.Type type = 1;
      public boolean hasType() {
        return result.hasType();
      }
      public org.devtcg.five.meta.data.Protos.Record.Type getType() {
        return result.getType();
      }
      public Builder setType(org.devtcg.five.meta.data.Protos.Record.Type value) {
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = org.devtcg.five.meta.data.Protos.Record.Type.ARTIST;
        return this;
      }
      
      // optional .Artist artist = 2;
      public boolean hasArtist() {
        return result.hasArtist();
      }
      public org.devtcg.five.meta.data.Protos.Artist getArtist() {
        return result.getArtist();
      }
      public Builder setArtist(org.devtcg.five.meta.data.Protos.Artist value) {
        result.hasArtist = true;
        result.artist_ = value;
        return this;
      }
      public Builder setArtist(org.devtcg.five.meta.data.Protos.Artist.Builder builderForValue) {
        result.hasArtist = true;
        result.artist_ = builderForValue.build();
        return this;
      }
      public Builder mergeArtist(org.devtcg.five.meta.data.Protos.Artist value) {
        if (result.hasArtist() &&
            result.artist_ != org.devtcg.five.meta.data.Protos.Artist.getDefaultInstance()) {
          result.artist_ =
            org.devtcg.five.meta.data.Protos.Artist.newBuilder(result.artist_).mergeFrom(value).buildPartial();
        } else {
          result.artist_ = value;
        }
        result.hasArtist = true;
        return this;
      }
      public Builder clearArtist() {
        result.hasArtist = false;
        result.artist_ = org.devtcg.five.meta.data.Protos.Artist.getDefaultInstance();
        return this;
      }
      
      // optional .Album album = 3;
      public boolean hasAlbum() {
        return result.hasAlbum();
      }
      public org.devtcg.five.meta.data.Protos.Album getAlbum() {
        return result.getAlbum();
      }
      public Builder setAlbum(org.devtcg.five.meta.data.Protos.Album value) {
        result.hasAlbum = true;
        result.album_ = value;
        return this;
      }
      public Builder setAlbum(org.devtcg.five.meta.data.Protos.Album.Builder builderForValue) {
        result.hasAlbum = true;
        result.album_ = builderForValue.build();
        return this;
      }
      public Builder mergeAlbum(org.devtcg.five.meta.data.Protos.Album value) {
        if (result.hasAlbum() &&
            result.album_ != org.devtcg.five.meta.data.Protos.Album.getDefaultInstance()) {
          result.album_ =
            org.devtcg.five.meta.data.Protos.Album.newBuilder(result.album_).mergeFrom(value).buildPartial();
        } else {
          result.album_ = value;
        }
        result.hasAlbum = true;
        return this;
      }
      public Builder clearAlbum() {
        result.hasAlbum = false;
        result.album_ = org.devtcg.five.meta.data.Protos.Album.getDefaultInstance();
        return this;
      }
      
      // optional .Song song = 4;
      public boolean hasSong() {
        return result.hasSong();
      }
      public org.devtcg.five.meta.data.Protos.Song getSong() {
        return result.getSong();
      }
      public Builder setSong(org.devtcg.five.meta.data.Protos.Song value) {
        result.hasSong = true;
        result.song_ = value;
        return this;
      }
      public Builder setSong(org.devtcg.five.meta.data.Protos.Song.Builder builderForValue) {
        result.hasSong = true;
        result.song_ = builderForValue.build();
        return this;
      }
      public Builder mergeSong(org.devtcg.five.meta.data.Protos.Song value) {
        if (result.hasSong() &&
            result.song_ != org.devtcg.five.meta.data.Protos.Song.getDefaultInstance()) {
          result.song_ =
            org.devtcg.five.meta.data.Protos.Song.newBuilder(result.song_).mergeFrom(value).buildPartial();
        } else {
          result.song_ = value;
        }
        result.hasSong = true;
        return this;
      }
      public Builder clearSong() {
        result.hasSong = false;
        result.song_ = org.devtcg.five.meta.data.Protos.Song.getDefaultInstance();
        return this;
      }
    }
    
    static {
      org.devtcg.five.meta.data.Protos.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Artist_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Artist_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Album_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Album_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Song_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Song_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Record_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Record_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\nfive.proto\"Y\n\006Artist\022\n\n\002id\030\001 \002(\003\022\020\n\010sy" +
      "ncTime\030\002 \002(\003\022\014\n\004mbid\030\003 \001(\t\022\014\n\004name\030\004 \002(\t" +
      "\022\025\n\rdiscoveryDate\030\005 \001(\003\"\177\n\005Album\022\n\n\002id\030\001" +
      " \002(\003\022\020\n\010syncTime\030\002 \002(\003\022\020\n\010artistId\030\003 \002(\003" +
      "\022\014\n\004mbid\030\004 \001(\t\022\014\n\004name\030\005 \002(\t\022\025\n\rdiscover" +
      "yDate\030\006 \001(\003\022\023\n\013releaseDate\030\007 \001(\003\"\270\001\n\004Son" +
      "g\022\n\n\002id\030\001 \002(\003\022\020\n\010syncTime\030\002 \002(\003\022\020\n\010artis" +
      "tId\030\003 \002(\003\022\017\n\007albumId\030\004 \002(\003\022\014\n\004mbid\030\005 \001(\t" +
      "\022\020\n\010mimeType\030\006 \001(\t\022\017\n\007bitrate\030\007 \001(\005\022\020\n\010f" +
      "ilesize\030\010 \001(\003\022\016\n\006length\030\t \001(\005\022\r\n\005title\030\n" +
      " \002(\t\022\r\n\005track\030\013 \001(\005\"\222\001\n\006Record\022\032\n\004type\030\001" +
      " \002(\0162\014.Record.Type\022\027\n\006artist\030\002 \001(\0132\007.Art" +
      "ist\022\025\n\005album\030\003 \001(\0132\006.Album\022\023\n\004song\030\004 \001(\013" +
      "2\005.Song\"\'\n\004Type\022\n\n\006ARTIST\020\001\022\t\n\005ALBUM\020\002\022\010" +
      "\n\004SONG\020\003B#\n\031org.devtcg.five.meta.dataB\006P" +
      "rotos";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Artist_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Artist_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Artist_descriptor,
              new java.lang.String[] { "Id", "SyncTime", "Mbid", "Name", "DiscoveryDate", },
              org.devtcg.five.meta.data.Protos.Artist.class,
              org.devtcg.five.meta.data.Protos.Artist.Builder.class);
          internal_static_Album_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Album_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Album_descriptor,
              new java.lang.String[] { "Id", "SyncTime", "ArtistId", "Mbid", "Name", "DiscoveryDate", "ReleaseDate", },
              org.devtcg.five.meta.data.Protos.Album.class,
              org.devtcg.five.meta.data.Protos.Album.Builder.class);
          internal_static_Song_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Song_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Song_descriptor,
              new java.lang.String[] { "Id", "SyncTime", "ArtistId", "AlbumId", "Mbid", "MimeType", "Bitrate", "Filesize", "Length", "Title", "Track", },
              org.devtcg.five.meta.data.Protos.Song.class,
              org.devtcg.five.meta.data.Protos.Song.Builder.class);
          internal_static_Record_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_Record_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Record_descriptor,
              new java.lang.String[] { "Type", "Artist", "Album", "Song", },
              org.devtcg.five.meta.data.Protos.Record.class,
              org.devtcg.five.meta.data.Protos.Record.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
